site_name: "MIDAS Python"
# site_url: "https://sumit-shekhar.github.io/midasapi-python/"
# site_description: "Documentation"
site_author: "Sumit Shekhar"
# repo_url: "https://github.com/Sumit-Shekhar/midasapi-python"
theme:
  name: shadcn
  # name : material
  # pygments_style: "github-dark"

  features:
    - navigation.indexes

nav:

  - Introduction: index.md
  - Model: model.md
  - Node: node.md

  - Element:
    - Element: Element/index.md
    - ‎ ‎ ‎ 1D Elements: Element/1D.md
    - ‎ ‎ ‎ 2D Elements: Element/2D.md

  - Section Properties:
    - Section : Section/index.md
    - ‎ ‎ ‎ Standard Section : Section/01_user.md
    - ‎ ‎ ‎ PSC Section: Section/02_psc.md
    - ‎ ‎ ‎ Composite Section : Section/03_composite.md
    - Thickness : Section/09_thickness.md

  - Material Properties:
    - Material : Material/index.md

    - ‎ ‎ ‎ Concrete : Material/001concrete.md
    - ‎ ‎ ‎ Steel : Material/002steel.md
    - ‎ ‎ ‎ User-defined : Material/003usermat.md

    - Creep Shrinkage : Material/010creep.md
    - Compressive Strength : Material/011comp.md
    - Time Dependent Link : Material/012tdlink.md  

  - Boundary Conditions:
    - Boundary : Boundary/index.md
    - ‎ ‎ ‎ Supports : Boundary/01supports.md
    - ‎ ‎ ‎ Elastic Link: Boundary/02elink.md
    - ‎ ‎ ‎ Rigid Link : Boundary/03rlink.md

  - Load:
    - Load : Load/index.md
    - ‎ ‎ ‎ Self Weight : Load/000sw.md
    - ‎ ‎ ‎ Nodal Load : Load/001nodal.md
    - ‎ ‎ ‎ Beam Load: Load/002beam.md
    - Load Case : Load/case.md
  
  - Group:
    - Group  : Group/index.md
    - ‎ ‎ ‎ Structure Group : Group/001sg.md
    - ‎ ‎ ‎ Boundary Group : Group/002bg.md
    - ‎ ‎ ‎ Load Group: Group/003lg.md
    - ‎ ‎ ‎ Tendon Group: Group/004tg.md

plugins:
  - search # put it first to inject out custom code

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - fenced_code
  - pymdownx.blocks.details